global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'  
        channel: '#all-finsuretech'  
        username: 'Alertmanager'
        title: '{{ .CommonAnnotations.summary }}'
        text: >-
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Severity:* {{ .Labels.severity }}
          *Status:* {{ .Status }}
          {{ end }}
